(keymap-unset evil-insert-state-map "C-k")

;; ==== Spacemacs Keys
(spacemacs/set-leader-keys "C-s" 'counsel-imenu)

(spacemacs/set-leader-keys "ie" 'emoji-cheat-sheet-plus-insert)
(spacemacs/set-leader-keys "jj" 'evil-avy-goto-word-or-subword-1)
(spacemacs/set-leader-keys "w=" 'tennyson/balance-windows-horizontally)
(spacemacs/declare-prefix "o" "personal keys")
(spacemacs/declare-prefix "oc" "clipboard")
(spacemacs/declare-prefix "oj" "javascript")
(spacemacs/declare-prefix "ot" "toggle")
(spacemacs/declare-prefix "ox" "execute")
(spacemacs/set-leader-keys "ocm" 'tennyson/org-pandoc-export-to-clipboard)
(spacemacs/set-leader-keys "ocp" 'tennyson-paste-to-clipboard)
(spacemacs/set-leader-keys "ocy" 'tennyson-copy-to-clipboard)
(spacemacs/set-leader-keys "of" 'tennyson/favorite-files)
(spacemacs/set-leader-keys "oiF" 'tennyson/firefox-insert-frontmost-link-and-close)
(spacemacs/set-leader-keys "oif" 'tennyson/firefox-insert-frontmost-link)
(spacemacs/set-leader-keys "oiwa" 'tennyson/firefox-insert-all-tabs)
(spacemacs/set-leader-keys "oiwc" 'tennyson/firefox-insert-frontmost-link-and-close)
(spacemacs/set-leader-keys "oiwf" 'tennyson/firefox-insert-frontmost-link)
(spacemacs/set-leader-keys "oiws" 'tennyson/firefox-ivy-select-and-close-tabs)
(spacemacs/set-leader-keys "oja" 'tennyson/jest-update-file)
(spacemacs/set-leader-keys "ooj" 'tennyson/jless-file-at-point)
(spacemacs/set-leader-keys "oot" 'tennyson/cmd-in-term)
(spacemacs/set-leader-keys "oov" 'tennyson/vd-file-at-point)
(spacemacs/set-leader-keys "or" 'tennyson/sh-send-line-or-region)
(spacemacs/set-leader-keys "ots" 'tennyson/toggle-invisible-search)
(spacemacs/set-leader-keys "ov" 'tennyson-paste-to-clipboard)
(spacemacs/set-leader-keys "oxc" 'tennyson/org-ref-jump-to-key)
(spacemacs/set-leader-keys "oxp" 'org-publish-all)
(spacemacs/set-leader-keys "oxs" 'tennyson/load-funcs)
(spacemacs/set-leader-keys "sC" 'evil-search-highlight-persist)
(spacemacs/set-leader-keys "xa#" 'spacemacs/align-repeat-hashtag)
(spacemacs/set-leader-keys "xax" 'align-regexp)
(spacemacs/set-leader-keys (kbd "x RET") 'link-hint-open-link-at-point)
(spacemacs/set-leader-keys-for-major-mode 'sh-mode "r" 'tennyson/sh-send-line-or-region)
(spacemacs/set-leader-keys-for-major-mode 'org-mode "ic" 'tennyson/org-ref-insert-cite-link)
(spacemacs/set-leader-keys-for-major-mode 'org-mode "iC" 'tennyson/add-reference)
(spacemacs/set-leader-keys-for-major-mode 'org-mode "hr" 'tennyson/sh-send-line-or-region)
(spacemacs/set-leader-keys-for-major-mode 'org-mode "ht" 'org-toggle-item)
(spacemacs/set-leader-keys-for-major-mode 'org-mode "hT" 'org-toggle-heading)
(spacemacs/set-leader-keys "pp" 'projectile-switch-project)


(defun tennyson/jless-file-at-point ()
  (interactive)
  (tennyson/cmd-in-term (format "jless %s" (ffap-file-at-point))))

(defun tennyson/vd-file-at-point ()
  (interactive)
  (tennyson/cmd-in-term (format "vd %s" (ffap-file-at-point))))

(spacemacs|create-align-repeat-x "hashtag" "#")

;; ==== High Priority Keys
(defun high-priority-keys ()
  (interactive)
  (define-key evil-normal-state-map ";" 'evil-avy-goto-word-or-subword-1)
  (define-key evil-visual-state-map ";" 'evil-avy-goto-word-or-subword-1)
  (define-key evil-normal-state-map "U" 'evil-jump-forward)
  (define-key evil-visual-state-map "U" 'evil-jump-forward)
  )
(high-priority-keys)
