(defun tennyson//start-term ()
  (interactive)
  (setq uuid (tennyson/uuidgen-4))
  (call-process "/bin/sh" nil nil nil "-c" (concat "tmux new-session -ds " uuid))
  (sit-for 0.5))

(defun tennyson//start-term-if-necessary ()
  (interactive)
  (if (boundp 'uuid)
      (unless (eq 0 (call-process "tmux" nil nil nil "has-session" "-t" uuid))
        (tennyson//start-term))
    (tennyson//start-term)))

(defun tennyson/sh-send-line-or-region ()
  (interactive ())
  (tennyson//start-term-if-necessary)
  (if (use-region-p)
      (setq min (region-beginning)
            max (region-end))
    (setq min (point-at-bol)
          max (point-at-eol)))
  (setq command (concat (buffer-substring min max) "\n"))
  (call-process "tmux" nil nil nil "send-keys" "-t" uuid "-l" command))
