(defun tennyson/yaml-setup ()
  (interactive)
  (yafolding-mode)
  (define-key evil-normal-state-map (kbd "z a") 'yafolding-toggle-element)
  (define-key evil-normal-state-map (kbd "z c") 'yafolding-hide-element)
  (define-key evil-normal-state-map (kbd "z o") 'yafolding-show-element)
  (define-key evil-normal-state-map (kbd "z M") 'yafolding-show-all)
  (define-key evil-normal-state-map (kbd "z R") 'yafolding-show-all)
  )
(add-hook 'yaml-mode 'tennyson/yaml-setup)
